# Generated by Django 4.2.3 on 2023-09-29 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=256, verbose_name='Name')),
                ('about', models.TextField()),
                ('experience', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=256)),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.study_center')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=256, verbose_name='Name')),
                ('about', models.TextField()),
                ('phone_number', models.CharField(max_length=256, verbose_name='Phone Number')),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.study_center')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
    ]
