# Generated by Django 4.2.5 on 2023-10-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fullname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='study_center',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='fullname',
            new_name='name',
        ),
    ]
